"""ARCTX path resolution for the git-native storage layout.

Run data lives **inside the repository** so that sharing is just git:
  <repo_root>/.arctx/runs/<run_id>/

Only the jsonl/json canon is meant to be committed; derived local files
(``run.cache.pkl``, ``run.db``, lock/temp files) are excluded by the
``.arctx/.gitignore`` that ``arctx init`` generates.

The "active run" pointer is a single file inside the git directory
(``<gitdir>/arctx-id``, one UUID line). It lives under ``.git/`` so git
itself never tracks it: there is no risk of accidental commits and no
``.gitignore`` plumbing is required. For ``git worktree`` checkouts the
pointer naturally ends up in the per-worktree gitdir, so each worktree
keeps its own active run.

Resolution priority for the run store directory (:func:`runs_dir`):
  1. ``ARCTX_HOME`` env var  -> ``${ARCTX_HOME}/runs``  (explicit override,
     used by tests and by tools that deliberately want out-of-repo storage)
  2. enclosing git repo      -> ``<repo_root>/.arctx/runs``  (the default)
  3. ``$XDG_DATA_HOME/arctx/runs`` / ``~/.local/share/arctx/runs``
     (fallback when not inside a git repo at all)

``resolve_arctx_home`` keeps its old, repo-independent meaning: it is the
location of the *user-level* ``config.json``, not of run data.
"""

from __future__ import annotations

import json
import os
from pathlib import Path


def resolve_arctx_home() -> Path:
    """Resolve ARCTX_HOME.

    Priority:
    1. ``ARCTX_HOME`` env var
    2. ``$XDG_DATA_HOME/arctx``
    3. ``~/.local/share/arctx``
    """
    env_home = os.environ.get("ARCTX_HOME")
    if env_home:
        return Path(env_home)
    xdg = os.environ.get("XDG_DATA_HOME")
    if xdg:
        return Path(xdg) / "arctx"
    return Path.home() / ".local/share/arctx"


ARCTX_DIR_NAME = ".arctx"

GITATTRIBUTES_LINES = (
    "* linguist-generated=true",
    "*.jsonl merge=union",
)

# Derived / machine-local artefacts that must never be committed. Patterns
# without a slash match at any depth below ``.arctx/``.
GITIGNORE_LINES = (
    "# Generated by `arctx init`. Derived, machine-local files: never commit.",
    "run.cache.pkl",
    "run.db",
    "run.db-journal",
    "run.db-wal",
    "run.db-shm",
    ".append.lock",
    ".cache_tmp_*",
    ".*.tmp_*",
)


def repo_arctx_dir(repo_root: Path) -> Path:
    """Return ``<repo_root>/.arctx``."""
    return repo_root / ARCTX_DIR_NAME


def repo_runs_dir(repo_root: Path) -> Path:
    """Return ``<repo_root>/.arctx/runs``."""
    return repo_arctx_dir(repo_root) / "runs"


def runs_dir(start: Path | None = None) -> Path:
    """Return the directory that holds run directories.

    See the module docstring for the resolution order: ``ARCTX_HOME``
    override, then the enclosing repo's ``.arctx/runs``, then the
    XDG/home fallback.
    """
    if os.environ.get("ARCTX_HOME"):
        return resolve_arctx_home() / "runs"
    try:
        return repo_runs_dir(find_repo_root(start))
    except RuntimeError:
        return resolve_arctx_home() / "runs"


def write_repo_git_metadata(repo_root: Path) -> dict[str, Path]:
    """Write ``.arctx/.gitattributes`` and ``.arctx/.gitignore`` idempotently.

    ``.gitattributes`` marks the whole tree as generated (so GitHub folds the
    diff) and gives jsonl files ``merge=union`` — the append-only, opaque-id,
    order-insensitive record model makes a line union the correct merge.

    Existing user lines are preserved; only missing lines are appended, so
    repeated ``arctx init`` runs never duplicate entries.
    """
    arctx_dir = repo_arctx_dir(repo_root)
    arctx_dir.mkdir(parents=True, exist_ok=True)
    written = {
        "gitattributes": _append_missing_lines(
            arctx_dir / ".gitattributes", GITATTRIBUTES_LINES
        ),
        "gitignore": _append_missing_lines(arctx_dir / ".gitignore", GITIGNORE_LINES),
    }
    return written


def _append_missing_lines(path: Path, lines: tuple[str, ...]) -> Path:
    existing: list[str] = []
    if path.exists():
        existing = path.read_text(encoding="utf-8").splitlines()
    present = {line.strip() for line in existing}
    missing = [line for line in lines if line not in present]
    if not missing:
        return path
    out = list(existing) + missing
    path.write_text("\n".join(out) + "\n", encoding="utf-8")
    return path


def resolve_git_dir(repo_root: Path) -> Path:
    """Return the real gitdir for *repo_root*.

    For a normal clone this is ``<repo_root>/.git``. For a linked
    worktree, ``<repo_root>/.git`` is a file containing
    ``gitdir: <path>`` and we follow it.
    """
    dot_git = repo_root / ".git"
    if dot_git.is_dir():
        return dot_git
    if dot_git.is_file():
        text = dot_git.read_text(encoding="utf-8").strip()
        for line in text.splitlines():
            if line.startswith("gitdir:"):
                target = Path(line.split(":", 1)[1].strip())
                if not target.is_absolute():
                    target = (repo_root / target).resolve()
                return target
    # Fallback: behave as if it were a directory (callers will error on
    # write if it truly does not exist).
    return dot_git


def arctx_id_path(repo_root: Path) -> Path:
    """Return the path to the active-run pointer for *repo_root*.

    The pointer lives at ``<gitdir>/arctx-id`` so git itself never tracks
    it.
    """
    return resolve_git_dir(repo_root) / "arctx-id"


def read_arctx_id(repo_root: Path) -> str | None:
    """Read the run id from the active-run pointer if present, else None.

    For one release we also fall back to the legacy ``<repo_root>/.arctx-id``
    location and silently migrate it into the gitdir on read, so existing
    checkouts keep working.
    """
    path = arctx_id_path(repo_root)
    if path.exists():
        text = path.read_text(encoding="utf-8").strip()
        return text if text else None

    legacy = repo_root / ".arctx-id"
    if legacy.exists():
        text = legacy.read_text(encoding="utf-8").strip()
        if not text:
            return None
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text + "\n", encoding="utf-8")
            legacy.unlink()
        except OSError:
            pass
        return text
    return None


def write_arctx_id(repo_root: Path, run_id: str) -> None:
    """Write *run_id* to the active-run pointer for *repo_root*."""
    path = arctx_id_path(repo_root)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(run_id + "\n", encoding="utf-8")
    # Clean up any stale legacy file if present.
    legacy = repo_root / ".arctx-id"
    if legacy.exists():
        try:
            legacy.unlink()
        except OSError:
            pass


def arctx_lane_path(repo_root: Path) -> Path:
    """Return the path to the active-lane pointer for *repo_root*.

    Mirrors :func:`arctx_id_path` for the run: the active lane lives at
    ``<gitdir>/arctx-lane`` so it persists across shells in the same checkout
    (the ``source .venv``-style "current lane") without git tracking it.
    """
    return resolve_git_dir(repo_root) / "arctx-lane"


def arctx_lanes_path(repo_root: Path) -> Path:
    """Return the per-run active-lane pointer map for *repo_root*."""
    return resolve_git_dir(repo_root) / "arctx-lanes.json"


def read_arctx_lane(repo_root: Path, run_id: str | None = None) -> str | None:
    """Read the lane id from the active-lane pointer if present, else None.

    When *run_id* is provided, prefer the per-run pointer map. The legacy
    single-lane pointer remains as a fallback for existing checkouts.
    """
    if run_id:
        lanes_path = arctx_lanes_path(repo_root)
        if lanes_path.exists():
            try:
                data = json.loads(lanes_path.read_text(encoding="utf-8"))
                lane = data.get(run_id) if isinstance(data, dict) else None
                if lane:
                    return str(lane)
            except (OSError, json.JSONDecodeError):
                pass
    path = arctx_lane_path(repo_root)
    if path.exists():
        text = path.read_text(encoding="utf-8").strip()
        return text if text else None
    return None


def write_arctx_lane(repo_root: Path, lane_id: str, run_id: str | None = None) -> None:
    """Write *lane_id* to the active-lane pointer for *repo_root*.

    With *run_id*, the pointer is stored in a per-run map so `--run other`
    does not accidentally reuse the last lane selected for a different run.
    The legacy single-lane pointer is also updated for compatibility with older
    callers and scripts.
    """
    if run_id:
        lanes_path = arctx_lanes_path(repo_root)
        lanes_path.parent.mkdir(parents=True, exist_ok=True)
        data: dict[str, str] = {}
        if lanes_path.exists():
            try:
                loaded = json.loads(lanes_path.read_text(encoding="utf-8"))
                if isinstance(loaded, dict):
                    data = {str(k): str(v) for k, v in loaded.items()}
            except (OSError, json.JSONDecodeError):
                data = {}
        data[run_id] = lane_id
        lanes_path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    path = arctx_lane_path(repo_root)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(lane_id + "\n", encoding="utf-8")


def find_repo_root(start: Path | None = None) -> Path:
    """Walk up from *start* (default: cwd) to find a ``.git`` entry.

    Accepts both a ``.git`` directory (normal clone) and a ``.git`` file
    (linked worktree).

    Raises
    ------
    RuntimeError
        If no ``.git`` entry is found before reaching the filesystem root.
    """
    current = (start or Path.cwd()).resolve()
    while True:
        if (current / ".git").exists():
            return current
        parent = current.parent
        if parent == current:
            raise RuntimeError(
                "not inside a git repository (no .git directory found). "
                "Run 'git init' first, or provide --run / ARCTX_RUN_ID."
            )
        current = parent


def resolve_store_dir(start: Path | None = None) -> str:
    """Return the run store directory as a string (see :func:`runs_dir`)."""
    return str(runs_dir(start))
